### PR TITLE
update to make it compile again under modern environment

### LINKED ISSUE #2: does not currently build
```
experimental_allocator 2.70.0-b1: building configuration "library"...
../../../.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(322,13): Error: std.experimental.allocator.common.Ternary at ../../../.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /Library/D/dmd/src/phobos/std/typecons.d(7427,1)
../../../.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(328,13): Error: std.experimental.allocator.common.Ternary at ../../../.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /Library/D/dmd/src/phobos/std/typecons.d(7427,1)
../../../.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(348,13): Error: std.experimental.allocator.common.Ternary at ../../../.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /Library/D/dmd/src/phobos/std/typecons.d(7427,1)
```

### PR DESCRIPTION
**Pull request by extrawurst**
(fixes #2)

### CODE REVIEW

**Comment by extrawurst** [comment]
the link to watch the failing screenshot does not work:
https://ddox-test-uploads.herokuapp.com/uploads/189889659

**Comment by MartinNowak** [comment]
thx, also switched the hosting of the image uploads
https://travis-ci.org/MartinNowak/scod/builds/191167973#L274-L284

**Comment by MartinNowak** [comment]
Oh, that update broke a few things, likely the templates in ddox changed enough.

**Comment by MartinNowak** [comment]
Was just an issue with generating the json file, no ddox changes in the few overriden view files.

**Pull request merged**
