### PR TITLE
Fix #18

### PR DESCRIPTION
**Pull request by Cyroxin**
Attempt to fix CI for #18

### CODE REVIEW

**Comment by Cyroxin** [comment]
@MartinNowak This fixes the CI errors, but fails the visual test. The tester itself seems to be broken.

**Comment by Cyroxin** [comment]
@MartinNowak Refreshing the ci build did not work, there is something that corrupts the visual tests, which I am unable to fix. If you wish to test the visual changes manually, here are some [docs](https://cyroxin.github.io/Elembuf/) that are using #18.

**Comment by MartinNowak** [comment]
The CI tests seem to work fine, here are the differences.

The code_example now has a deactivated scrollbar.
[image](https://img.vim-cn.com/c0/f92ee3cecb7f6c741c0e922cacbbae085b99c8.png)

The class_main_content now has function signatures, seems unrelated to your PR (maybe newer ddox or compiler) and OKish IMHO.
[image](https://img.vim-cn.com/45/5fbeed223b375347d70ed235daf1c7d1839fbd.png)

**Comment by Cyroxin** [comment]
Ah, looks like I wrote "scroll" instead of "auto". I had it correctly in the docs, but not in the PR.

**Comment by Cyroxin** [comment]
Ready to merge. "code_example" test now passes. @MartinNowak

**Pull request merged**
